export const WORDING_FR = {
  // Language Menu
  'language_option_fra': 'Français (France)',
  'language_option_eng': 'Anglais (États-Unis)',
  // Landing
  'landing_title': 'Bienvenue sur le portfolio de Tony Herbet Le Faucheur',
  'landing_text_1': 'Ce site a été pensé et réalisé pour une utilisation sur ordinateur, je vous invite donc à le faire si ce n\'est pas le cas.',
  'landing_text_2': 'Le concept est d\'émuler un système d\'exploitation et de naviguer dessus comme tel.',
  'landing_text_3': 'Pour voir directement mes informations, vous pouvez cliquer sur l\'icone contenant l\'inscription "pdf" ce qui ouvrira mon curriculum vitae.',
  'landing_text_4': 'Pour me contacter par e-mail, cliquer sur l\'icone en forme de "M".',  
  'landing_text_5': 'Je vous laisse découvrir le reste des fonctionnalités.',
  'landing_text_6': 'Pour commencer l\'expérience, merci de cliquer sur le bouton ci-dessous.',
  'landing_start_button': 'Démarrer',
  // Loader
  'loader_text': 'Le système d\'exploitation est en cours de démarrage...',
  'loader_button_skip': 'Passer',
  // Mail
  'mail_title': 'Me contacter',
  'mail_name': 'Votre nom',
  'mail_email': 'Votre adresse e-mail',
  'mail_message': 'Votre message',
  'mail_success': 'Merci, votre e-mail à bien été envoyé',
  'mail_error': 'Un problème est survenu, veuillez essayer de nouveau dans quelques instants',
  'mail_fields_error': 'Tous les champs doivent être remplis',
  'mail_send_button': 'Envoyer',
  // Settings
  'settings_frameHeader_name': 'Paramètres',
  'settings_tab_colors' : 'Couleurs',
  'settings_tab_background' : 'Fond d\'écran',
  'settings_theme_label' : 'Choisissez votre mode',
  'settings_theme_light' : 'Clair',
  'settings_theme_dark' : 'Sombre',
  'settings_theme_accent_choice' : 'Choisissez une couleur d\'accentuation',
  'settings_theme_accent_current' : 'Couleur actuelle',
  'settings_theme_background_current' : 'Fond d\'écran actuel',
  'settings_theme_background_choice' : 'Choisissez un fond d\'écran',
  // Folder
  'folder_frameHeader_name': 'Explorateur de fichiers',
  // TxtReader
  'txtReader_file': 'Fichier',
  'txtReader_edit': 'Edition',
  'txtReader_view': 'Affichage',
  'txtReader_settings': 'Paramètres',
  // PDF
  'pdf_error_text_1': 'Il semble que vous ne puissiez pas voir le fichier PDF, ',
  'pdf_error_text_2': ' cliquez ici pour le voir ou le télécharger.',
  // Terminal
  'terminal_header_text': "PowerBash, version -8000.0.0 alpha Vous pouvez exécuter des commandes. Tapez 'help' pour voir la liste des commandes.",
  'terminal_cd_root_error': 'vous êtes déjà dans le répertoire racine, vous ne pouvez pas remonter',
  'terminal_cd_path_error': "la commande 'cd' a besoin d'un nom de répertoire, tapez 'ls' pour voir tous les répertoires ou 'help' pour voir toutes les commandes",
  'terminal_cd_directory_error': "répertoire '$CMDOPTION' introuvable, tapez 'ls' pour voir tous les répertoires ou 'help' pour voir toutes les commandes",
  'terminal_open_name_error': "la commande 'open' nécessite un nom de fichier, tapez 'ls' pour voir tous les fichiers du répertoire actuel ou 'help' pour voir toutes les commandes",
  'terminal_open_not_found_error': "fichier '$CMDOPTION' introuvable, tapez 'ls' pour voir tous les fichiers du répertoire courant ou 'help' pour voir toutes les commandes",
  'terminal_cmd_not_fount_error': "commande '$INPUTVALUE' introuvable, tapez 'help' pour voir toutes les commandes",
  // Data
  'presentation_name': 'Présentation.txt',
  'presentation_text': 'Présentation FRANCAIS Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ad dolorum pariatur porro modi, quod quisquam doloremque nulla repellat inventore repellendus. Omnis possimus harum voluptatibus officia illum repellat enim vel deleniti!',
  'competences_name': 'Compétences.txt',
  'competences_text': 'Compétences FRANCAIS',
  'formation_dwwm_name': 'Formation_dwwm.txt',
  'formation_dwwm_text': 'Formation_dwwm FRANCAIS',
  'opquast_name': 'Opquast.txt',
  'opquast_text': 'Opquast FRANCAIS',
  'dwwm_name': 'DWWM.txt',
  'dwwm_text': 'DWWM FRANCAIS',
  'p3fc_name': 'P3FC.txt',
  'p3fc_text': 'P3FC FRANCAIS',
  'otd_name': 'Old_The_Door.txt',
  'otd_text': 'Old_The_Door FRANCAIS',
  'cv_name': 'CV.pdf',
  'diplomas_name': 'Diplômes',
  'projects_name': 'Projets',
}