export const WORDING_EN = {
  // Language Menu
  'language_option_fra': 'French (France)',
  'language_option_eng': 'English (United States)',
  // Landing
  'landing_title': 'Welcome to the portfolio of Tony Herbet Le Faucheur',
  'landing_text_1': 'This site was designed and created to be use on a computer, so I invite you to do so if this is not the case.',
  'landing_text_2': 'The concept is to emulate an operating system and navigate on it as such.',
  'landing_text_3': 'To directly see my information, you can click on the icon containing the inscription "pdf" which will open my personal resume.',
  'landing_text_4': 'To contact me by email, click on the "M" shaped icon..',  
  'landing_text_5': 'I\'ll let you discover the rest of the features.',
  'landing_text_6': 'To start the experience, please click on the button below.',
  'landing_start_button': 'Start',
  // Loader
  'loader_text': 'The operating system is booting...',
  'loader_button_skip': 'Skip',
  // Mail
  'mail_title': 'Contact me',
  'mail_name': 'Your name',
  'mail_email': 'Your email adress',
  'mail_message': 'Your message',
  'mail_success': 'Thank you, your email has been sent',
  'mail_error': 'Something went wrong, please try again in a few moments',
  'mail_fields_error': 'All fields must be filled',
  'mail_send_button': 'Send',
  // Settings
  'settings_frameHeader_name': 'Settings',
  'settings_tab_colors' : 'Colors',
  'settings_tab_background' : 'Background',
  'settings_theme_label' : 'Choose a theme',
  'settings_theme_light' : 'Light',
  'settings_theme_dark' : 'Dark',
  'settings_theme_accent_choice' : 'Choose an accent color',
  'settings_theme_accent_current' : 'Current color',
  'settings_theme_background_current' : 'Current background',
  'settings_theme_background_choice' : 'Choose a background',
  // Folder
  'folder_frameHeader_name': 'File explorer',
  // TxtReader
  'txtReader_file': 'File',
  'txtReader_edit': 'Edit',
  'txtReader_view': 'View',
  'txtReader_settings': 'Settings',
  // PDF
  'pdf_error_text_1': 'It appears you can\'t see the PDF file, ',
  'pdf_error_text_2': 'click here to see or download it.',
  // Terminal
  'terminal_header_text': "PowerBash, version -8000.0.0 alpha You can run commands. Type 'help' to see the list of commands.",
  'terminal_cd_root_error': 'you are already in the root directory you cannot move up',
  'terminal_cd_path_error': "the 'cd' command need a directory name, type 'ls' to see all the directories or 'help' to see all the commands",
  'terminal_cd_directory_error': "directory '$CMDOPTION' not found, type 'ls' to see all the directories or 'help' to see all the commands",
  'terminal_open_name_error': "'open' command need a file name, type 'ls' to see all the files in current directory or 'help' to see all the commands",
  'terminal_open_not_found_error': "file '$CMDOPTION' not found, type 'ls' to see all the files in current directory or 'help' to see all the commands",
  'terminal_cmd_not_fount_error': "command '$INPUTVALUE' not found, type 'help' to see all the commands",
  // Data
  'presentation_name': 'Presentation.txt',
  'presentation_text': 'Présentation ENGLISH Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ad dolorum pariatur porro modi, quod quisquam doloremque nulla repellat inventore repellendus. Omnis possimus harum voluptatibus officia illum repellat enim vel deleniti!',
  'competences_name': 'Competences.txt',
  'competences_text': 'Competences ENGLISH',
  'formation_dwwm_name': 'Formation_dwwm.txt',
  'formation_dwwm_text': 'Formation_dwwm ENGLISH',
  'opquast_name': 'Opquast.txt',
  'opquast_text': 'Opquast ENGLISH',
  'dwwm_name': 'DWWM.txt',
  'dwwm_text': 'DWWM ENGLISH',
  'p3fc_name': 'P3FC.txt',
  'p3fc_text': 'P3FC ENGLISH',
  'otd_name': 'Old_The_Door.txt',
  'otd_text': 'Old_The_Door ENGLISH',
  'cv_name': 'Résumé.pdf',
  'diplomas_name': 'Diplomas',
  'projects_name': 'Projects',
}